<!doctype html>
<html lang="en">
    <div>
        <img src="https://i.ibb.co/XLQJ6vd/Screenshot-2022-11-13-135108.png" style="width:100%"></img>     
        <table border="1" cellspacing="0" cellpadding="1" style="width:100%">
            <tr class="tableHeader">
                <td><b>Invoice Number</b></td>
                <td><b>Order Date</b></td>
                <td><b>Order Number</b></td>
            </tr>               
            <tr class="tableBody">
                <td>${invoiceId}</td>
                <td>${orderDate}</td>
                <td>${orderNumber}</td>
            </tr>                        
        </table> 
    </div>
</html> 